<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0c3884d-f9f8-4174-9fe7-47646b6bb46f</elementGuidId>
    <imagePath></imagePath>
    <name>link_SauceLabsFleeceJacket</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_5_title_link') and equals(@href,'#') and equals(@text,'Sauce Labs Fleece Jacket')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_5_title_link</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Fleece Jacket</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
</WebElementEntity>