<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1aad1432-ae19-4668-83d8-d1e076e649e4</elementGuidId>
    <imagePath></imagePath>
    <name>link_AllItems</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/nav[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'inventory_sidebar_link') and equals(@href,'#') and equals(@text,'All Items')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>inventory_sidebar_link</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>All Items</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
</WebElementEntity>