<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>94c7e772-e4e2-4b84-b443-267cd0664774</elementGuidId>
    <imagePath></imagePath>
    <name>button_BackHome</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'back-to-products') and equals(@name,'back-to-products') and equals(@text,'Back Home')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Back Home</value>
        <webElementGuid>294fa09b-ddbf-4c39-8f96-cbc1b31e0471</webElementGuid>
    </webElementProperties>
</WebElementEntity>